server:
  #Jetty默认是非阻塞的，可以处理更多并发请求
  jetty:
    threads:
      #acceptors线程接收http  请求
      acceptors: 4
      #selectors 线程池负责处理HTTP消息协议数据包
      selectors: 8
      #worker线程池负责调用web方法
      min: 8
      max: 200
  port: 8088
  servlet:
    context-path: /hospital-wx
#  address: 192.168.205.252
#  address: 10.77.75.14
spring:
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://47.108.146.141:8765;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      #上传的文件不能超过20m
      max-file-size: 20MB
      #http请求不能超过20M
      max-request-size: 20MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #        连接池最大连接数
        max-active: 1000
        #        连接池最大阻塞等待时间
        max-wait: -1ms
        #        连接池最大空闲连接
        max-idle: 16
        #        最小空闲连接
        min-idle: 8

  quartz:
    job-store-type: memory
  rabbitmq:
    host: 47.108.146.141
    port: 15672
    username: admin
    password: admin
    #返回JSON的全局时间格式
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  application:
    name: hospital-api

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  #http请求头中token的名称
  token-name: token
  #token有效期，单位s，默认30天，-1代表永不过期
  timeout: 7200
  #token临时有效期
  activity-timeout: -1
  #是否允许同一账号并发登录
  allow-concurrent-login: true
  #在多人登录同一账号时，是否共用一个token
  is-share: false
  #token的风格
  token-style: uuid
  #读取Cookie中Token
  isReadCookie: false


wechat:

  app-id: wx9d10622612e17575
  app-secret: 43b41fcae69a262d01a939b2761d5fef

#配置TRTC
tencent:
  cloud:
    appId: 1308174688
    secretId: AKIDVTFn8F8pIXZMvGUUHrDMG1YqwoUAcrrc
    secretKey: c1DBwQp21pyzoRr21qW1NZWFjIgvyraC
    face:
      groupName: hospital
      region: ap-chongqing
  trtc:
    appId: 1400799601
    secretKey: 33703ed1aba792643f11846de7165924c38155ba923bbd99250b80df49918b81
    expire: 86400

minio:
  endpoint: http://47.108.146.141:9000
  access-key: admin
  secret-key: minio@zy.com




